### ISSUE TITLE
Setting for selecting the fonts available

### ISSUE THREAD

**Issue by izendegi** [mediamaisteri/moodle-tiny_fontfamily#1]
Hi,

I've discovered this plugin while searching for a Tiny alternative of [atto_fontfamily](https://moodle.org/plugins/atto_fontfamily), and when testing it I've realized that, unlike that other plugin, currently this plugin doesn't give a setting to define the fonts available for the user.

Having that setting is very useful to give admins the choice of selecting the fonts available.

**Comment by haiksu** [comment]
> Hi,
> 
> I've discovered this plugin while searching for a Tiny alternative of [atto_fontfamily](https://moodle.org/plugins/atto_fontfamily), and when testing it I've realized that, unlike that other plugin, currently this plugin doesn't give a setting to define the fonts available for the user.
> 
> Having that setting is very useful to give admins the choice of selecting the fonts available.

Makes sense - I'll get on it.

**Comment by haiksu** [comment]
PR merged, cheers & happy testing!

**Comment by izendegi** [comment]
Great, thank you @haiksu!

**Comment by izendegi** [comment]
Hi again, @haiksu 

Now that the plugin has been approved in [the plugin database](https://moodle.org/plugins/tiny_fontfamily), could you please update it with the latest version that includes this functionality?

Thank you!

**Comment by haiksu** [comment]
There you go @izendegi  https://moodle.org/plugins/tiny_fontfamily/1.0.1/34089.
Have a good one!
